### PR TITLE
add typings for GithubCorner component

### PR DESCRIPTION
**Pull request by maracuja-juice**
I use this in a TypeScript project of mine and needed to create typings for it. In order to make it easier for other Typescript users to use this component I added the typings here.

### CODE REVIEW

**Comment by skratchdot** [comment]
Awesome! Thank you!  I will merge and publish soon.

**Comment by skratchdot** [comment]
Thanks @maracuja-juice !  I just published v2.2.0: https://www.npmjs.com/package/react-github-corner

**Comment by maracuja-juice** [comment]
Hey cool thanks!
There's still something though that I haven't done correctly with the typings. I'll look into it and submit a new pull when I found out what it is.

**Comment by skratchdot** [comment]
I think I just need to add:
```
"types": "./lib/GithubCorner.d.ts"
```
to the package.json per:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I'll take a look, but will need you to help test if you can :)

**Comment by skratchdot** [comment]
Actually, just moving that file to `index.d.ts` in the root should fix it.  I think I prefer that.  I will try and re-publish.

**Comment by skratchdot** [comment]
@maracuja-juice - I just published version 2.3.0.  Can you try re-testing?

**Comment by maracuja-juice** [comment]
@skratchdot That works perfectly! Thanks a lot for your time 👍

**Pull request merged**
